image: kopppcappp/archlinux-yaourt:latest

pipelines:
  default:
    - step:
        script:
          - pacman -Syy
          - pacman --noconfirm -S clang
          - pacman --noconfirm -S gtest
          - pacman --noconfirm -S cmake
          - CXX=g++ ./run_tests.sh
          - CXX=clang++ ./run_tests.sh
